services:
  backend:
    image: backend:${TAG}
    container_name: backend-${TAG}
    restart: always
    networks:
      - server-tools_default
  
  frontend:
    image: frontend:${TAG}
    container_name: frontend-${TAG}
    restart: always
    networks:
      - server-tools_default

ai-service:
    image: ai:${TAG}
    container_name: okkul-ai
    restart: always
    ports:
      - "8000:8000"
    networks:
      server-tools_default:
        aliases:
          - okkul-ai-develop  # http://okkul-ai-develop:8000으로 호출 가능

networks:
  server-tools_default:
    external: true
