services:
  backend:
    image: backend:${TAG}
    container_name: backend-${TAG}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
    networks:
      - server-tools_default
  
  frontend:
    image: frontend:${TAG}
    container_name: frontend-${TAG}
    restart: always
    networks:
      - server-tools_default

networks:
  server-tools_default:
    external: true
