services:
  # 1. PostgreSQL (DB)
  postgres:
    image: postgres:16.11
    container_name: local-postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"  # 내 컴퓨터에서만 접속 가능
    environment:
      POSTGRES_USER: postgres  # 개발용이니 기본 계정 사용
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: okkul_db

  # 2. Redis (Cache)
  redis:
    image: redis:7.2-alpine
    container_name: local-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"  # 내 컴퓨터에서만 접속 가능
    command: redis-server
